spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/valandro/spring-cloud-config.git
          skip-ssl-validation: true
server:
  port: 9028
  servlet:
    context-path: /config-server